(Testing)

diff --git a/.github/workflows/build-push-test.yaml b/.github/workflows/build-push-test.yaml
--- a/.github/workflows/build-push-test.yaml
+++ b/.github/workflows/build-push-test.yaml
@@ -110,6 +110,22 @@ jobs:
       # - name: Install jq
       #   run: sudo snap install jq
 
+      # docker cp "$CONTAINER_ID:/root/.ollama/models/blobs/sha256" ./model-blobs
+
+      - name: Test model file (inspect only)
+        run: |
+          IMAGE_NAME=model-servers/ollama-server-${{ needs.build.outputs.model_name }}:${{ needs.build.outputs.model_tag }}
+          CONTAINER_ID=$(docker create "$IMAGE_NAME")
+          docker cp "$CONTAINER_ID:/root/.ollama/models/" ./model-blobs
+          docker rm "$CONTAINER_ID"
+          if [ -z "$(ls -A ./model-blobs)" ]; then
+            echo "Model not found in image"
+            exit 1
+          else
+            echo "Model files found:"
+            ls ./model-blobs
+          fi
+
       - name: Test model library (inspect only)
         run: |
           IMAGE_NAME=model-servers/ollama-server-${{ needs.build.outputs.model_name }}:${{ needs.build.outputs.model_tag }}
@@ -131,22 +147,6 @@ jobs:
             echo "$MODEL_ENTRY"
           fi
 
-
-      # docker cp "$CONTAINER_ID:/root/.ollama/models/blobs/sha256" ./model-blobs
-
-      - name: Test model file (inspect only)
-        run: |
-          IMAGE_NAME=model-servers/ollama-server-${{ needs.build.outputs.model_name }}:${{ needs.build.outputs.model_tag }}
-          CONTAINER_ID=$(docker create "$IMAGE_NAME")
-          docker cp "$CONTAINER_ID:/root/.ollama/models/blobs" ./model-blobs
-          docker rm "$CONTAINER_ID"
-          if [ -z "$(ls -A ./model-blobs)" ]; then
-            echo "Model not found in image"
-            exit 1
-          else
-            echo "Model files found:"
-            ls ./model-blobs
-          fi
 
       # - name: Test model preload
       #   run: |
