(Testing) Use static artifact name

diff --git a/.github/workflows/build-push-test.yaml b/.github/workflows/build-push-test.yaml
--- a/.github/workflows/build-push-test.yaml
+++ b/.github/workflows/build-push-test.yaml
@@ -72,13 +72,13 @@ jobs:
 
       - name: Save Docker image as artifact
         run: |
-          docker save model-servers/ollama-server-$MODEL_NAME:$MODEL_TAG -o ollama-server-image.tar
+          docker save model-servers/ollama-server-$MODEL_NAME:$MODEL_TAG -o ollama-server.tar
 
       - name: Upload image artifact
         uses: actions/upload-artifact@v4
         with:
-          name: ollama-server-image-${{ env.MODEL_NAME }}-${{ env.MODEL_TAG }}
-          path: ollama-server-${{ env.MODEL_NAME }}-${{ env.MODEL_TAG }}.tar
+          name: ollama-server
+          path: ollama-server.tar
 
   test:
     needs: build
@@ -87,7 +87,7 @@ jobs:
       - name: Download image artifact
         uses: actions/download-artifact@v4
         with:
-          name: ollama-server-image-${{ needs.build.outputs.model_name }}-${{ needs.build.outputs.model_tag }}
+          name: ollama-server
       - name: Load Docker image
         run: |
           docker load -i ollama-server.tar
@@ -95,7 +95,7 @@ jobs:
 
       - name: Test model file
         run: |
-          docker run --rm model-servers/ollama-server-${{ needs.build.outputs.model_name }}:${{ needs.build.outputs.model_tag }} sh -c 'ls /root/.ollama/models/blobs/sha256/ | grep . || (echo "Model not found" && exit 1)'
+          docker run --rm model-servers/ollama-server sh -c 'ls /root/.ollama/models/blobs/sha256/ | grep . || (echo "Model not found" && exit 1)'
       # - name: Test model preload
       #   run: |
       #     docker run --rm model-servers/ollama-server-$MODEL_NAME:$MODEL_TAG curl -s http://localhost:11434/api/generate -d '{"model": "'"$MODEL_NAME""}',"prompt":"2 + 2 ="}' || (echo "Model not loaded" && exit 1)
@@ -109,7 +109,7 @@ jobs:
       - name: Download image artifact
         uses: actions/download-artifact@v4
         with:
-          name: ollama-server-image-${{ needs.build.outputs.model_name }}-${{ needs.build.outputs.model_tag }}
+          name: ollama-server
 
       - name: Load Docker image
         run: |
